Repository KendallDoesCoding/quiz, pull requests merged in 2023-03, with the labels that each got.

#37 fixed the bug that was caused only option B to be correct
  pages/browsers/game.html
  pages/christmas/game.html
  pages/countries/game.html
  pages/disney/game.html
  pages/easter/game.html
  pages/football/game.html
  pages/fruit/game.html
  pages/game.html
  pages/general_knowledge/game.html
  pages/kendall-quiz/game.html
  pages/minecraft/game.html
  pages/presidents/game.html
  pages/roblox/game.html
  pages/tech/game.html
Labels: size/S

#45 added a quiz in pages, created a directory in js/data .
  README.md
  js/data/Programminglanguage.js
  js/data/index.js
  pages/programming_language/game.html
  pages/programming_language/index.html
  pages/topics.html
Labels: size/L

#48 Fix typo
  README.md
Labels: size/XS
