Repository KendallDoesCoding/quiz, pull requests merged in 2023-12, with the labels that each got.

#76 Fixed cursor pointer in Quiz topic section
  css/index.css
Labels: size/XS

#70 adding of points distribution
  css/game.css
  css/index.css
  css/topics.css
  js/QuizClass.js
  js/christmas-songs.js
  js/data/index.js
  js/data/instruments.js
  js/rules.js
  js/songs.js
  js/topics.js
  package-lock.json
  pages/browsers/game.html
  pages/christmas/game.html
  pages/computer_parts/game.html
  pages/countries/game.html
  pages/disney/game.html
  pages/easter/game.html
  pages/football/game.html
  pages/fruit/game.html
  pages/game.html
  pages/general_knowledge/game.html
  pages/instruments/game.html
  pages/instruments/index.html
  pages/jaidenanimations/game.html
  pages/kendall-quiz/game.html
  pages/minecraft/game.html
  pages/presidents/game.html
  pages/programming_language/game.html
  pages/roblox/game.html
  pages/tech/game.html
  pages/theodd1sout/game.html
  pages/topics.html
  pages/youtube/game.html
Labels: size/XXL

#79 added contributing guidelines
  .github/CONTRIBUTING.md
  README.md
Labels: size/L

#80 Updated email address
  .github/CONTRIBUTING.md
Labels: size/XS
